idf_component_register(
    SRCS
        "main.c"
        "components/board_init.c"
        "components/SD.cpp"
        "components/opencalc_breakout.c"
        "components/opencalc_doom.c"
        "components/opencalc_mario.cpp"
        "components/opencalc_math.c"
        "components/opencalc_persist.c"
        "components/opencalc_power.c"
        "components/opencalc_snake.c"
        "components/opencalc_tetris.c"
        "components/opencalc_ui.c"
        "components/storage.c"
        "components/usb_msc.c"
        "components/tiny-python.c"
        "components/mario/bus.cpp"
        "components/mario/cartridge.cpp"
        "components/mario/cpu6502.cpp"
        "components/mario/mapper.cpp"
        "components/mario/ppu2C02.cpp"
        "components/mario/mappers/mapper000.cpp"
        "components/doomgeneric/am_map.c"
        "components/doomgeneric/doomdef.c"
        "components/doomgeneric/doomgeneric.c"
        "components/doomgeneric/doomstat.c"
        "components/doomgeneric/dstrings.c"
        "components/doomgeneric/d_event.c"
        "components/doomgeneric/d_items.c"
        "components/doomgeneric/d_iwad.c"
        "components/doomgeneric/d_loop.c"
        "components/doomgeneric/d_main.c"
        "components/doomgeneric/d_mode.c"
        "components/doomgeneric/d_net.c"
        "components/doomgeneric/dummy.c"
        "components/doomgeneric/f_finale.c"
        "components/doomgeneric/f_wipe.c"
        "components/doomgeneric/g_game.c"
        "components/doomgeneric/hu_lib.c"
        "components/doomgeneric/hu_stuff.c"
        "components/doomgeneric/i_cdmus.c"
        "components/doomgeneric/i_endoom.c"
        "components/doomgeneric/i_input.c"
        "components/doomgeneric/i_joystick.c"
        "components/doomgeneric/i_scale.c"
        "components/doomgeneric/i_sound.c"
        "components/doomgeneric/i_system.c"
        "components/doomgeneric/i_timer.c"
        "components/doomgeneric/i_video.c"
        "components/doomgeneric/info.c"
        "components/doomgeneric/m_argv.c"
        "components/doomgeneric/m_bbox.c"
        "components/doomgeneric/m_cheat.c"
        "components/doomgeneric/m_config.c"
        "components/doomgeneric/m_controls.c"
        "components/doomgeneric/m_fixed.c"
        "components/doomgeneric/m_menu.c"
        "components/doomgeneric/m_misc.c"
        "components/doomgeneric/m_random.c"
        "components/doomgeneric/memio.c"
        "components/doomgeneric/p_ceilng.c"
        "components/doomgeneric/p_doors.c"
        "components/doomgeneric/p_enemy.c"
        "components/doomgeneric/p_floor.c"
        "components/doomgeneric/p_inter.c"
        "components/doomgeneric/p_lights.c"
        "components/doomgeneric/p_map.c"
        "components/doomgeneric/p_maputl.c"
        "components/doomgeneric/p_mobj.c"
        "components/doomgeneric/p_plats.c"
        "components/doomgeneric/p_pspr.c"
        "components/doomgeneric/p_saveg.c"
        "components/doomgeneric/p_setup.c"
        "components/doomgeneric/p_sight.c"
        "components/doomgeneric/p_spec.c"
        "components/doomgeneric/p_switch.c"
        "components/doomgeneric/p_telept.c"
        "components/doomgeneric/p_tick.c"
        "components/doomgeneric/p_user.c"
        "components/doomgeneric/r_bsp.c"
        "components/doomgeneric/r_data.c"
        "components/doomgeneric/r_draw.c"
        "components/doomgeneric/r_main.c"
        "components/doomgeneric/r_plane.c"
        "components/doomgeneric/r_segs.c"
        "components/doomgeneric/r_sky.c"
        "components/doomgeneric/r_things.c"
        "components/doomgeneric/s_sound.c"
        "components/doomgeneric/sha1.c"
        "components/doomgeneric/sounds.c"
        "components/doomgeneric/statdump.c"
        "components/doomgeneric/st_lib.c"
        "components/doomgeneric/st_stuff.c"
        "components/doomgeneric/tables.c"
        "components/doomgeneric/v_video.c"
        "components/doomgeneric/w_checksum.c"
        "components/doomgeneric/w_file.c"
        "components/doomgeneric/w_file_stdc.c"
        "components/doomgeneric/w_main.c"
        "components/doomgeneric/w_wad.c"
        "components/doomgeneric/wi_stuff.c"
        "components/doomgeneric/z_zone.c"
    INCLUDE_DIRS
        "./components"
        "./components/doomgeneric"
    REQUIRES
        driver
        esp_driver_ledc
        esp_adc
        esp_timer
        esp_lcd
        esp_pm
        nvs_flash
        fatfs 
        wear_levelling 
        esp_tinyusb
)

target_compile_definitions(${COMPONENT_LIB} PRIVATE PY_MAX_TOKENS=128)
target_compile_definitions(${COMPONENT_LIB} PRIVATE DOOMGENERIC_RESX=320 DOOMGENERIC_RESY=200)
target_compile_definitions(${COMPONENT_LIB} PRIVATE COMPOSITE_VIDEO=1 OPENCALC_NONBLOCKING_DOOM_TICS=1)
target_compile_options(${COMPONENT_LIB} PRIVATE
    -Wno-error
    -Wno-dangling-pointer
    -Wno-format
    -Wno-format-truncation
    -Wno-implicit-fallthrough
    -Wno-error=missing-field-initializers
    -Wno-error=unterminated-string-initialization
    -Wno-error=format
    -Wno-error=format-truncation
    -Wno-error=implicit-fallthrough
    -Wno-error=type-limits
    -Wno-error=unused-but-set-parameter
    -Wno-error=unused-variable
    -Wno-error=unused-const-variable
    -Wno-missing-field-initializers
    -Wno-type-limits
    -Wno-unused-but-set-parameter
    -Wno-unused-but-set-variable
    -Wno-unused-const-variable
    -Wno-unused-variable
)
